<h2 class="orange">What CMS is best for your small - medium business?</h2>
<div class="article bg-opacity">
	<p class="orange-text"><strong>Wordpress</strong></p>
	<p>WordPress is one of (if not the most) popular CMS's used today.  It's a free open source CMS which actually originated as a blogging platform in 2003.</p>
		<div class="italic-references">[BuiltWith September 2015]</div>
	<p>This CMS is in my opinion one of the easiest to use that is self-installed and hosted.  The user interface is pretty straight forward with most of your options on the left column after you login to the admin section.  These options let you configure anything from the look of your website which is called a 'Theme', to the content that's in it like your text or pictures, and many other options including blog posts and comment maintenance, technical/backend type settings and plugins.</p>
	<p>Plugins are what makes the system so extensible, and there are tens of thousands today which cover many categories from social media, to games, to SEO (Search Engine Optimization) and e-commerce; some are free, some are purchased.</p>
	<p>Themes are based on a looping mechanism which is what the blog posts were originally based around, but the good news is you don't need a blog to use WordPress.  The 'Loop' connects all the pieces of the template together that are basically split up into header, content, sidebar and footer, with additional parts like 'comment form' and 'search form' available which are mainly for blog posts.</p>
		<div class="italic-references">[Wordpress (n.d.)]</div>
	<p>Now there are some drawbacks of WordPress, and this includes the security issues it has with malicious attacks and also the lack of official support (it is free open-source after all).  Because of the popularity of the system, it does tend to get attacked by hackers quite a bit, and because it's open-source these hackers have the ability to learn the system and its vulnerabilities.  Although WordPress creators do the best to patch these vulnerabilities up, it takes time for them to release these patches.</p>
	<p>Another bad point is that the plugins mentioned earlier are sometimes abandoned, so they aren't updated to fix security vulnerabilities or to work correctly with the latest version of the CMS which is quite frustrating.</p>
	<p class="orange-text"><strong>Drupal</strong></p>
	<p>A more advanced and also open-source CMS option is Drupal who claims to have an endless variety of customization.  This CMS is used by well-known large companies including Yahoo, AOL, Warner Brothers Records and even the White House!</p>
		<div class="italic-references">[Fiedler, D. 2010]</div>
	<p>Drupal, unlike WordPress has a dedicated security team.  You can actually report security issues that the team will investigate, and who also will get back to you and inform you as to what you can do to fix a security issue.  They also co-ordinate and release security announcements that refer to issues that are going to be fixed/patched days in advance.</p>
	<p>This system is more aimed at advanced users because of the complexity, and this can be seen in the structure of their template files.</p>
	<p>Similar to WordPress in the sense that parts of the page are separated into blocks, there are a lot more functions and variables present and these require you to track down their origins to understand how exactly to modify the given variables or complex arrays it comes with. </p>
		<div class="italic-references">[Luisi, J. March 2012]</div>
	<p>Going further from the chaotic data structure, there are many levels of processing or pre-processing here too, what a nightmare!</p>
	<p class="orange-text"><strong>ExpressionEngine</strong></p>
	<p>ExpressionEngine is a professional CMS system that unlike the free options mentioned previously, comes at a price, from $99US to $299US.</p>
	<p>This CMS is quite designer friendly because of its 'flexibility and lack of required mark-up, which means designers rarely have to accommodate the CMS in their designs'.</p>
		<div class="italic-references">[Boyink, M (n.d.)]</div>
	<p> The extensive control and complete separation of code and content is great because it lets you control most of the styling with pure CSS rather than wrapping the CMS around the code.</p>
		<div class="italic-references">[Neto, M. March 2010]</div>
	<p>The way ExpressionEngine goes about building of the site is completely opposite to WordPress and Drupal which base theirs around pages first, content later.  Working from what's referred to as 'Structured Content' (which is great for SEO) is how EE works.</p>
	<p>Using a Structured Content approach makes the site content much easier to manage and reuse.  When you have smaller blocks of information to work with and each of these blocks has a particular purpose, it makes your site much easier to update bit by bit rather than spending more time trying to update an entire page.  EE calls these 'Channels', which are made up by 'category' and 'channel' names, 'field' columns and 'entry' rows.</p>
	<p> This gives your pages more meaning and purpose, and provides a potentially better overall user experience.</p>
	<p>The ROI on this CMS could be better than say WordPress or Drupal as you have official support from dedicated developers, saving you a lot of time and money on developer contracting. The only time you would require an external developer is when you want to completely update the website look or layout, and that's the downfall.  Unlike WordPress where you could update your overall theme in say 20 minutes, you'd have to jump through loops to do that in EE.</p>
	<p class="orange-text"><strong>Magento</strong></p>
	<p>Magento is the leading solution and widest used e-commerce CMS platform.</p>
		<div class="italic-references">[comScore (n.d.)]</div>
	<p>If your business intends to utilise e-commerce then this is the best option for an e-commerce CMS platform, depending what option you choose that is.</p>
	<p>Magento has two options available, the Community Edition (free) and the Enterprise Edition (paid).  The Community Edition is an open-source CMS that can be installed onto your own hosted server just like WordPress, or for around $49US it can be hosted on the Magento servers.</p>
	<p>The paid edition will set you back considerably at around $18, 000 per year, well out of most small to medium business's budget.  Most developers will charge through the roof for developing these sites too, so unless you have a dedicated I.T. department or have some tech-savvy skills in house, your pocket is going to hurt here too.  The Enterprise Edition option is really only for larger companies.</p>
	<p>You can extend the functionality of either edition with plugins just like other CMS's, though the system itself is very feature rich and more advanced than WordPress e-commerce plugins such as wooCommerce.</p>
		<div class="italic-references">[Barron, B. March 2015]</div>
	<p class="orange-text"><strong>Shopify</strong></p>
	<p>Lastly, another CMS e-commerce option is Shopify.</p>
	<p>Shopify was based off an e-commerce business that wanted to sell snowboard equipment online but didn't have a decent tool to do so, so they built their own.</p>
	<p>This CMS is sort of a turn-key option, so if you're needing to set something up quickly with ease, you shouldn't go any further.  You don't need developers to set up hosting and security and so forth, it's all done on Shopify and handled by professionals, and only for a bare fraction of the price charged by contractors.</p>
	<p>Shopify has similar features to the other e-commerce CMS's such as plugins and order processing, though it lacks a little in templates and customization.  But where it lacks in customization it makes up for in speed, and this is a crucial factor for all websites really, especially when you have potential paying customers who are likely to leave a site that loads slowly and shop elsewhere.</p>
		<div class="italic-references">[Shivar, N June 2015]</div>
	<p>The price ranges from $9US a month to $179US for the complete package.  Note there are extra fees charged for things like transactions, certain transaction gateway plugins which you'll need for Australian shops, and other add on packages.</p>
		<div class="italic-references">[Shopify (n.d.)]</div>
	<p class="orange-text"><strong>So, which one is for you?</strong></p>
	<p>The choice of CMS for your small to medium business depends on your situation.</p>
	<p><b>WordPress</b>: Probably the best option for a small to medium business that either doesn't require e-commerce or only a simple implementation.  Hire a professional developer to set this up initially and you should be fine from there with only the occasional help needed when you want to make changes.  Be prepared though, it may be cheap in the short-run, but end up costing more down the track.</p>
	<p><b>Drupal</b>: Unless you're quite tech-savvy or have a permanent I.T. person/developer/programmer already on hand, this option could get quite costly.  Even getting the website set up by a developer would be a little more costly because of the complexity of work to set up, and to fix when things go wrong.</p>
	<p><b>ExpressionEngine</b>: If you want to invest some money initially and have a website that is better content focused and easier to update, this is a great option.  EE may have a better ROI in the long run because of the costs saved with support and maintenance.</p>
	<p><b>Magento</b>: If your serious about e-commerce, look no further, but don't go for the Enterprise Edition because let's face it, the cost is just insane!  Get a developer to set this up for you, though they tend to charge more for these sites so expect a solid bill.  Once you're set up though, this CMS has the potential for success!</p>
	<p><b>Shopify</b>: Your turn-key option for an e-commerce site.  No fuss, no contract developers, but also little customization.  Pay your month to month fees and your set, but in the long term it may not have the best ROI when your business grows and you're still being charged per transaction fees.</p>

	<div class="orange-text" style="text-align:center;"><p>Bibliography</p></div>
	<ul>
		<li>BuiltWith September 2015, accessed 17 September 2015,
			<br>[<a href="http://trends.builtwith.com/cms" target="_blank">http://trends.builtwith.com/cms</a>]</li>
		<li>Wordpress (n.d.), accessed 17 September 2015,
			<br>[<a href="https://codex.wordpress.org/Stepping_into_Templates" target="_blank">https://codex.wordpress.org/Stepping_into_Templates</a>]</li>
		<li>Fiedler, D. 2010, accessed 17 September 2015,
			<br>[<a href="http://www.htmlgoodies.com/beyond/webmaster/toolbox/article.php/3882296" target="_blank">http://www.htmlgoodies.com/beyond/webmaster/toolbox/article.php/3882296</a>]</li>
		<li>Luisi, J. March 2012, accessed 17 September 2015,
			<br>[<a href="http://jacine.net/post/19652705220/theme-system" target="_blank">http://jacine.net/post/19652705220/theme-system</a>]</li>
		<li>Boyink, M (n.d.), accessed 17 September 2015,
			<br>[<a href="http://www.train-ee.com/courseware/expressionengine-at-a-glance" target="_blank">http://www.train-ee.com/courseware/expressionengine-at-a-glance</a>]</li>
		<li>Neto, M. March 2010, accessed 17 September 2015,
			<br>[<a href="http://www.webdesignerdepot.com/2010/03/wordpress-vs-expressionengine-apples-and-oranges/" target="_blank">http://www.webdesignerdepot.com/2010/03/wordpress-vs-expressionengine-apples-and-oranges/</a>]</li>
		<li>comScore (n.d.), accessed 17 September 2015,
			<br>[<a href="http://cometrics.co/statistics/magento-usage/" target="_blank">http://cometrics.co/statistics/magento-usage/</a>]</li>
		<li>Barron, B. March 2015, accessed 17 September 2015,
			<br>[<a href="https://www.elegantthemes.com/blog/resources/woocommerce-vs-magento-which-e-commerce-platform-is-right-for-you" target="_blank">https://www.elegantthemes.com/blog/resources/woocommerce-vs-magento-which-e-commerce-platform-is-right-for-you</a>]</li>
		<li>Shivar, N June 2015, accessed 17 September 2015,
			<br>[<a href="http://www.shivarweb.com/2748/shopify-review-pros-cons-of-using-shopify-for-ecommerce/" target="_blank">http://www.shivarweb.com/2748/shopify-review-pros-cons-of-using-shopify-for-ecommerce/</a>]</li>
		<li>Shopify (n.d.), accessed 17 September 2015,
			<br>[<a href="https://www.shopify.com.au/pricing" target="_blank">https://www.shopify.com.au/pricing</a>]</li>
	</ul>
	<p class="orange-text">Wordcount: 1489</p>
</div> <!-- end div class article -->