<div class="center-hw-box bg-opacity">
	<h2 class="black-orange">Menu</h2>
	<div class="form-buttons">
		<form name="moviezone-menu" id="admin-menu" action="moviezone.php" method="get">
			<input type="submit" name="search" value="New Releases">
			<input type="submit" name="search" value="Show All Movies">
			<input type="submit" name="search" value="Search by Actor">
			<input type="submit" name="search" value="Search by Director">
			<input type="submit" name="search" value="Search by Genre">
			<input type="submit" name="search" value="Search by Classification">
		</form>
	</div>
</div>